CREATE TABLE USUARIO_ROLES (
    usuario_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, role_id),
    CONSTRAINT FK_USUARIO FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id) ON DELETE CASCADE,
    CONSTRAINT FK_ROLE FOREIGN KEY (role_id) REFERENCES ROLES(id) ON DELETE CASCADE
);
